package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewAddBuildFileParams creates a new AddBuildFileParams object
// with the default values initialized.
func NewAddBuildFileParams() *AddBuildFileParams {
	var ()
	return &AddBuildFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddBuildFileParamsWithTimeout creates a new AddBuildFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddBuildFileParamsWithTimeout(timeout time.Duration) *AddBuildFileParams {
	var ()
	return &AddBuildFileParams{

		timeout: timeout,
	}
}

// NewAddBuildFileParamsWithContext creates a new AddBuildFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddBuildFileParamsWithContext(ctx context.Context) *AddBuildFileParams {
	var ()
	return &AddBuildFileParams{

		Context: ctx,
	}
}

// NewAddBuildFileParamsWithHTTPClient creates a new AddBuildFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddBuildFileParamsWithHTTPClient(client *http.Client) *AddBuildFileParams {
	var ()
	return &AddBuildFileParams{
		HTTPClient: client,
	}
}

/*AddBuildFileParams contains all the parameters to send to the API endpoint
for the add build file operation typically these are written to a http.Request
*/
type AddBuildFileParams struct {

	/*BuildFilePost
	  build file to add

	*/
	BuildFilePost *models.BuildFilePost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add build file params
func (o *AddBuildFileParams) WithTimeout(timeout time.Duration) *AddBuildFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add build file params
func (o *AddBuildFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add build file params
func (o *AddBuildFileParams) WithContext(ctx context.Context) *AddBuildFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add build file params
func (o *AddBuildFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add build file params
func (o *AddBuildFileParams) WithHTTPClient(client *http.Client) *AddBuildFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add build file params
func (o *AddBuildFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildFilePost adds the buildFilePost to the add build file params
func (o *AddBuildFileParams) WithBuildFilePost(buildFilePost *models.BuildFilePost) *AddBuildFileParams {
	o.SetBuildFilePost(buildFilePost)
	return o
}

// SetBuildFilePost adds the buildFilePost to the add build file params
func (o *AddBuildFileParams) SetBuildFilePost(buildFilePost *models.BuildFilePost) {
	o.BuildFilePost = buildFilePost
}

// WriteToRequest writes these params to a swagger request
func (o *AddBuildFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BuildFilePost == nil {
		o.BuildFilePost = new(models.BuildFilePost)
	}

	if err := r.SetBodyParam(o.BuildFilePost); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
