// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewArchivePartSupportConfigurationParams creates a new ArchivePartSupportConfigurationParams object
// with the default values initialized.
func NewArchivePartSupportConfigurationParams() *ArchivePartSupportConfigurationParams {
	var ()
	return &ArchivePartSupportConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewArchivePartSupportConfigurationParamsWithTimeout creates a new ArchivePartSupportConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewArchivePartSupportConfigurationParamsWithTimeout(timeout time.Duration) *ArchivePartSupportConfigurationParams {
	var ()
	return &ArchivePartSupportConfigurationParams{

		timeout: timeout,
	}
}

// NewArchivePartSupportConfigurationParamsWithContext creates a new ArchivePartSupportConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewArchivePartSupportConfigurationParamsWithContext(ctx context.Context) *ArchivePartSupportConfigurationParams {
	var ()
	return &ArchivePartSupportConfigurationParams{

		Context: ctx,
	}
}

// NewArchivePartSupportConfigurationParamsWithHTTPClient creates a new ArchivePartSupportConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewArchivePartSupportConfigurationParamsWithHTTPClient(client *http.Client) *ArchivePartSupportConfigurationParams {
	var ()
	return &ArchivePartSupportConfigurationParams{
		HTTPClient: client,
	}
}

/*ArchivePartSupportConfigurationParams contains all the parameters to send to the API endpoint
for the archive part support configuration operation typically these are written to a http.Request
*/
type ArchivePartSupportConfigurationParams struct {

	/*PartID
	  ID of part

	*/
	PartID int32
	/*SupportConfigurationID
	  ID of support configuration to get

	*/
	SupportConfigurationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) WithTimeout(timeout time.Duration) *ArchivePartSupportConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) WithContext(ctx context.Context) *ArchivePartSupportConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) WithHTTPClient(client *http.Client) *ArchivePartSupportConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPartID adds the partID to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) WithPartID(partID int32) *ArchivePartSupportConfigurationParams {
	o.SetPartID(partID)
	return o
}

// SetPartID adds the partId to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) SetPartID(partID int32) {
	o.PartID = partID
}

// WithSupportConfigurationID adds the supportConfigurationID to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) WithSupportConfigurationID(supportConfigurationID int32) *ArchivePartSupportConfigurationParams {
	o.SetSupportConfigurationID(supportConfigurationID)
	return o
}

// SetSupportConfigurationID adds the supportConfigurationId to the archive part support configuration params
func (o *ArchivePartSupportConfigurationParams) SetSupportConfigurationID(supportConfigurationID int32) {
	o.SupportConfigurationID = supportConfigurationID
}

// WriteToRequest writes these params to a swagger request
func (o *ArchivePartSupportConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param partId
	if err := r.SetPathParam("partId", swag.FormatInt32(o.PartID)); err != nil {
		return err
	}

	// path param supportConfigurationId
	if err := r.SetPathParam("supportConfigurationId", swag.FormatInt32(o.SupportConfigurationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
