// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelMicrostructureSimulationParams creates a new CancelMicrostructureSimulationParams object
// with the default values initialized.
func NewCancelMicrostructureSimulationParams() *CancelMicrostructureSimulationParams {
	var ()
	return &CancelMicrostructureSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelMicrostructureSimulationParamsWithTimeout creates a new CancelMicrostructureSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelMicrostructureSimulationParamsWithTimeout(timeout time.Duration) *CancelMicrostructureSimulationParams {
	var ()
	return &CancelMicrostructureSimulationParams{

		timeout: timeout,
	}
}

// NewCancelMicrostructureSimulationParamsWithContext creates a new CancelMicrostructureSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelMicrostructureSimulationParamsWithContext(ctx context.Context) *CancelMicrostructureSimulationParams {
	var ()
	return &CancelMicrostructureSimulationParams{

		Context: ctx,
	}
}

// NewCancelMicrostructureSimulationParamsWithHTTPClient creates a new CancelMicrostructureSimulationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelMicrostructureSimulationParamsWithHTTPClient(client *http.Client) *CancelMicrostructureSimulationParams {
	var ()
	return &CancelMicrostructureSimulationParams{
		HTTPClient: client,
	}
}

/*CancelMicrostructureSimulationParams contains all the parameters to send to the API endpoint
for the cancel microstructure simulation operation typically these are written to a http.Request
*/
type CancelMicrostructureSimulationParams struct {

	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) WithTimeout(timeout time.Duration) *CancelMicrostructureSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) WithContext(ctx context.Context) *CancelMicrostructureSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) WithHTTPClient(client *http.Client) *CancelMicrostructureSimulationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) WithID(id int32) *CancelMicrostructureSimulationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cancel microstructure simulation params
func (o *CancelMicrostructureSimulationParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CancelMicrostructureSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
