package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelSingleBeadSimulationParams creates a new CancelSingleBeadSimulationParams object
// with the default values initialized.
func NewCancelSingleBeadSimulationParams() *CancelSingleBeadSimulationParams {
	var ()
	return &CancelSingleBeadSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelSingleBeadSimulationParamsWithTimeout creates a new CancelSingleBeadSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelSingleBeadSimulationParamsWithTimeout(timeout time.Duration) *CancelSingleBeadSimulationParams {
	var ()
	return &CancelSingleBeadSimulationParams{

		timeout: timeout,
	}
}

// NewCancelSingleBeadSimulationParamsWithContext creates a new CancelSingleBeadSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelSingleBeadSimulationParamsWithContext(ctx context.Context) *CancelSingleBeadSimulationParams {
	var ()
	return &CancelSingleBeadSimulationParams{

		Context: ctx,
	}
}

/*CancelSingleBeadSimulationParams contains all the parameters to send to the API endpoint
for the cancel single bead simulation operation typically these are written to a http.Request
*/
type CancelSingleBeadSimulationParams struct {

	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel single bead simulation params
func (o *CancelSingleBeadSimulationParams) WithTimeout(timeout time.Duration) *CancelSingleBeadSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel single bead simulation params
func (o *CancelSingleBeadSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel single bead simulation params
func (o *CancelSingleBeadSimulationParams) WithContext(ctx context.Context) *CancelSingleBeadSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel single bead simulation params
func (o *CancelSingleBeadSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the cancel single bead simulation params
func (o *CancelSingleBeadSimulationParams) WithID(id int32) *CancelSingleBeadSimulationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cancel single bead simulation params
func (o *CancelSingleBeadSimulationParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CancelSingleBeadSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
