package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelAssumedStrainSimulationParams creates a new CancelAssumedStrainSimulationParams object
// with the default values initialized.
func NewCancelAssumedStrainSimulationParams() *CancelAssumedStrainSimulationParams {
	var ()
	return &CancelAssumedStrainSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelAssumedStrainSimulationParamsWithTimeout creates a new CancelAssumedStrainSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelAssumedStrainSimulationParamsWithTimeout(timeout time.Duration) *CancelAssumedStrainSimulationParams {
	var ()
	return &CancelAssumedStrainSimulationParams{

		timeout: timeout,
	}
}

// NewCancelAssumedStrainSimulationParamsWithContext creates a new CancelAssumedStrainSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelAssumedStrainSimulationParamsWithContext(ctx context.Context) *CancelAssumedStrainSimulationParams {
	var ()
	return &CancelAssumedStrainSimulationParams{

		Context: ctx,
	}
}

/*CancelAssumedStrainSimulationParams contains all the parameters to send to the API endpoint
for the cancel assumed strain simulation operation typically these are written to a http.Request
*/
type CancelAssumedStrainSimulationParams struct {

	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel assumed strain simulation params
func (o *CancelAssumedStrainSimulationParams) WithTimeout(timeout time.Duration) *CancelAssumedStrainSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel assumed strain simulation params
func (o *CancelAssumedStrainSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel assumed strain simulation params
func (o *CancelAssumedStrainSimulationParams) WithContext(ctx context.Context) *CancelAssumedStrainSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel assumed strain simulation params
func (o *CancelAssumedStrainSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the cancel assumed strain simulation params
func (o *CancelAssumedStrainSimulationParams) WithID(id int32) *CancelAssumedStrainSimulationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cancel assumed strain simulation params
func (o *CancelAssumedStrainSimulationParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CancelAssumedStrainSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
