// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// DeletePorositySimulationReader is a Reader for the DeletePorositySimulation structure.
type DeletePorositySimulationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePorositySimulationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePorositySimulationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeletePorositySimulationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeletePorositySimulationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeletePorositySimulationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeletePorositySimulationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePorositySimulationOK creates a DeletePorositySimulationOK with default headers values
func NewDeletePorositySimulationOK() *DeletePorositySimulationOK {
	return &DeletePorositySimulationOK{}
}

/*DeletePorositySimulationOK handles this case with default header values.

Successfully deleted a simulation
*/
type DeletePorositySimulationOK struct {
}

func (o *DeletePorositySimulationOK) Error() string {
	return fmt.Sprintf("[DELETE /porositysimulations/{id}][%d] deletePorositySimulationOK ", 200)
}

func (o *DeletePorositySimulationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePorositySimulationUnauthorized creates a DeletePorositySimulationUnauthorized with default headers values
func NewDeletePorositySimulationUnauthorized() *DeletePorositySimulationUnauthorized {
	return &DeletePorositySimulationUnauthorized{}
}

/*DeletePorositySimulationUnauthorized handles this case with default header values.

Not authorized
*/
type DeletePorositySimulationUnauthorized struct {
	Payload *models.Error
}

func (o *DeletePorositySimulationUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /porositysimulations/{id}][%d] deletePorositySimulationUnauthorized  %+v", 401, o.Payload)
}

func (o *DeletePorositySimulationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePorositySimulationForbidden creates a DeletePorositySimulationForbidden with default headers values
func NewDeletePorositySimulationForbidden() *DeletePorositySimulationForbidden {
	return &DeletePorositySimulationForbidden{}
}

/*DeletePorositySimulationForbidden handles this case with default header values.

Forbidden
*/
type DeletePorositySimulationForbidden struct {
	Payload *models.Error
}

func (o *DeletePorositySimulationForbidden) Error() string {
	return fmt.Sprintf("[DELETE /porositysimulations/{id}][%d] deletePorositySimulationForbidden  %+v", 403, o.Payload)
}

func (o *DeletePorositySimulationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePorositySimulationNotFound creates a DeletePorositySimulationNotFound with default headers values
func NewDeletePorositySimulationNotFound() *DeletePorositySimulationNotFound {
	return &DeletePorositySimulationNotFound{}
}

/*DeletePorositySimulationNotFound handles this case with default header values.

Not Found
*/
type DeletePorositySimulationNotFound struct {
}

func (o *DeletePorositySimulationNotFound) Error() string {
	return fmt.Sprintf("[DELETE /porositysimulations/{id}][%d] deletePorositySimulationNotFound ", 404)
}

func (o *DeletePorositySimulationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePorositySimulationDefault creates a DeletePorositySimulationDefault with default headers values
func NewDeletePorositySimulationDefault(code int) *DeletePorositySimulationDefault {
	return &DeletePorositySimulationDefault{
		_statusCode: code,
	}
}

/*DeletePorositySimulationDefault handles this case with default header values.

unexpected error
*/
type DeletePorositySimulationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete porosity simulation default response
func (o *DeletePorositySimulationDefault) Code() int {
	return o._statusCode
}

func (o *DeletePorositySimulationDefault) Error() string {
	return fmt.Sprintf("[DELETE /porositysimulations/{id}][%d] DeletePorositySimulation default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePorositySimulationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
