// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePartSupportParams creates a new DeletePartSupportParams object
// with the default values initialized.
func NewDeletePartSupportParams() *DeletePartSupportParams {
	var ()
	return &DeletePartSupportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePartSupportParamsWithTimeout creates a new DeletePartSupportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePartSupportParamsWithTimeout(timeout time.Duration) *DeletePartSupportParams {
	var ()
	return &DeletePartSupportParams{

		timeout: timeout,
	}
}

// NewDeletePartSupportParamsWithContext creates a new DeletePartSupportParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePartSupportParamsWithContext(ctx context.Context) *DeletePartSupportParams {
	var ()
	return &DeletePartSupportParams{

		Context: ctx,
	}
}

// NewDeletePartSupportParamsWithHTTPClient creates a new DeletePartSupportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePartSupportParamsWithHTTPClient(client *http.Client) *DeletePartSupportParams {
	var ()
	return &DeletePartSupportParams{
		HTTPClient: client,
	}
}

/*DeletePartSupportParams contains all the parameters to send to the API endpoint
for the delete part support operation typically these are written to a http.Request
*/
type DeletePartSupportParams struct {

	/*PartID
	  ID of part

	*/
	PartID int32
	/*SupportID
	  ID of support to get

	*/
	SupportID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete part support params
func (o *DeletePartSupportParams) WithTimeout(timeout time.Duration) *DeletePartSupportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete part support params
func (o *DeletePartSupportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete part support params
func (o *DeletePartSupportParams) WithContext(ctx context.Context) *DeletePartSupportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete part support params
func (o *DeletePartSupportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete part support params
func (o *DeletePartSupportParams) WithHTTPClient(client *http.Client) *DeletePartSupportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete part support params
func (o *DeletePartSupportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPartID adds the partID to the delete part support params
func (o *DeletePartSupportParams) WithPartID(partID int32) *DeletePartSupportParams {
	o.SetPartID(partID)
	return o
}

// SetPartID adds the partId to the delete part support params
func (o *DeletePartSupportParams) SetPartID(partID int32) {
	o.PartID = partID
}

// WithSupportID adds the supportID to the delete part support params
func (o *DeletePartSupportParams) WithSupportID(supportID int32) *DeletePartSupportParams {
	o.SetSupportID(supportID)
	return o
}

// SetSupportID adds the supportId to the delete part support params
func (o *DeletePartSupportParams) SetSupportID(supportID int32) {
	o.SupportID = supportID
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePartSupportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param partId
	if err := r.SetPathParam("partId", swag.FormatInt32(o.PartID)); err != nil {
		return err
	}

	// path param supportId
	if err := r.SetPathParam("supportId", swag.FormatInt32(o.SupportID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
