package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// GetSimulationActivityReader is a Reader for the GetSimulationActivity structure.
type GetSimulationActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSimulationActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSimulationActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetSimulationActivityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetSimulationActivityForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSimulationActivityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSimulationActivityOK creates a GetSimulationActivityOK with default headers values
func NewGetSimulationActivityOK() *GetSimulationActivityOK {
	return &GetSimulationActivityOK{}
}

/*GetSimulationActivityOK handles this case with default header values.

Successfully found the item
*/
type GetSimulationActivityOK struct {
	Payload *models.SimulationActivity
}

func (o *GetSimulationActivityOK) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/activities/{activityId}][%d] getSimulationActivityOK  %+v", 200, o.Payload)
}

func (o *GetSimulationActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimulationActivity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSimulationActivityUnauthorized creates a GetSimulationActivityUnauthorized with default headers values
func NewGetSimulationActivityUnauthorized() *GetSimulationActivityUnauthorized {
	return &GetSimulationActivityUnauthorized{}
}

/*GetSimulationActivityUnauthorized handles this case with default header values.

Not authorized
*/
type GetSimulationActivityUnauthorized struct {
	Payload *models.Error
}

func (o *GetSimulationActivityUnauthorized) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/activities/{activityId}][%d] getSimulationActivityUnauthorized  %+v", 401, o.Payload)
}

func (o *GetSimulationActivityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSimulationActivityForbidden creates a GetSimulationActivityForbidden with default headers values
func NewGetSimulationActivityForbidden() *GetSimulationActivityForbidden {
	return &GetSimulationActivityForbidden{}
}

/*GetSimulationActivityForbidden handles this case with default header values.

Forbidden
*/
type GetSimulationActivityForbidden struct {
	Payload *models.Error
}

func (o *GetSimulationActivityForbidden) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/activities/{activityId}][%d] getSimulationActivityForbidden  %+v", 403, o.Payload)
}

func (o *GetSimulationActivityForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSimulationActivityDefault creates a GetSimulationActivityDefault with default headers values
func NewGetSimulationActivityDefault(code int) *GetSimulationActivityDefault {
	return &GetSimulationActivityDefault{
		_statusCode: code,
	}
}

/*GetSimulationActivityDefault handles this case with default header values.

unexpected error
*/
type GetSimulationActivityDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get simulation activity default response
func (o *GetSimulationActivityDefault) Code() int {
	return o._statusCode
}

func (o *GetSimulationActivityDefault) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/activities/{activityId}][%d] getSimulationActivity default  %+v", o._statusCode, o.Payload)
}

func (o *GetSimulationActivityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
