// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPartSupportConfigurationParams creates a new GetPartSupportConfigurationParams object
// with the default values initialized.
func NewGetPartSupportConfigurationParams() *GetPartSupportConfigurationParams {
	var ()
	return &GetPartSupportConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPartSupportConfigurationParamsWithTimeout creates a new GetPartSupportConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPartSupportConfigurationParamsWithTimeout(timeout time.Duration) *GetPartSupportConfigurationParams {
	var ()
	return &GetPartSupportConfigurationParams{

		timeout: timeout,
	}
}

// NewGetPartSupportConfigurationParamsWithContext creates a new GetPartSupportConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPartSupportConfigurationParamsWithContext(ctx context.Context) *GetPartSupportConfigurationParams {
	var ()
	return &GetPartSupportConfigurationParams{

		Context: ctx,
	}
}

// NewGetPartSupportConfigurationParamsWithHTTPClient creates a new GetPartSupportConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPartSupportConfigurationParamsWithHTTPClient(client *http.Client) *GetPartSupportConfigurationParams {
	var ()
	return &GetPartSupportConfigurationParams{
		HTTPClient: client,
	}
}

/*GetPartSupportConfigurationParams contains all the parameters to send to the API endpoint
for the get part support configuration operation typically these are written to a http.Request
*/
type GetPartSupportConfigurationParams struct {

	/*PartID
	  ID of part

	*/
	PartID int32
	/*SupportConfigurationID
	  ID of support configuration to get

	*/
	SupportConfigurationID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get part support configuration params
func (o *GetPartSupportConfigurationParams) WithTimeout(timeout time.Duration) *GetPartSupportConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get part support configuration params
func (o *GetPartSupportConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get part support configuration params
func (o *GetPartSupportConfigurationParams) WithContext(ctx context.Context) *GetPartSupportConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get part support configuration params
func (o *GetPartSupportConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get part support configuration params
func (o *GetPartSupportConfigurationParams) WithHTTPClient(client *http.Client) *GetPartSupportConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get part support configuration params
func (o *GetPartSupportConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPartID adds the partID to the get part support configuration params
func (o *GetPartSupportConfigurationParams) WithPartID(partID int32) *GetPartSupportConfigurationParams {
	o.SetPartID(partID)
	return o
}

// SetPartID adds the partId to the get part support configuration params
func (o *GetPartSupportConfigurationParams) SetPartID(partID int32) {
	o.PartID = partID
}

// WithSupportConfigurationID adds the supportConfigurationID to the get part support configuration params
func (o *GetPartSupportConfigurationParams) WithSupportConfigurationID(supportConfigurationID int32) *GetPartSupportConfigurationParams {
	o.SetSupportConfigurationID(supportConfigurationID)
	return o
}

// SetSupportConfigurationID adds the supportConfigurationId to the get part support configuration params
func (o *GetPartSupportConfigurationParams) SetSupportConfigurationID(supportConfigurationID int32) {
	o.SupportConfigurationID = supportConfigurationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPartSupportConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param partId
	if err := r.SetPathParam("partId", swag.FormatInt32(o.PartID)); err != nil {
		return err
	}

	// path param supportConfigurationId
	if err := r.SetPathParam("supportConfigurationId", swag.FormatInt32(o.SupportConfigurationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
