package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPartParams creates a new GetPartParams object
// with the default values initialized.
func NewGetPartParams() *GetPartParams {
	var ()
	return &GetPartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPartParamsWithTimeout creates a new GetPartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPartParamsWithTimeout(timeout time.Duration) *GetPartParams {
	var ()
	return &GetPartParams{

		timeout: timeout,
	}
}

// NewGetPartParamsWithContext creates a new GetPartParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPartParamsWithContext(ctx context.Context) *GetPartParams {
	var ()
	return &GetPartParams{

		Context: ctx,
	}
}

/*GetPartParams contains all the parameters to send to the API endpoint
for the get part operation typically these are written to a http.Request
*/
type GetPartParams struct {

	/*ID
	  ID of part to get

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get part params
func (o *GetPartParams) WithTimeout(timeout time.Duration) *GetPartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get part params
func (o *GetPartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get part params
func (o *GetPartParams) WithContext(ctx context.Context) *GetPartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get part params
func (o *GetPartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the get part params
func (o *GetPartParams) WithID(id int32) *GetPartParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get part params
func (o *GetPartParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
