// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// GetSingleBeadSimulationChildrenReader is a Reader for the GetSingleBeadSimulationChildren structure.
type GetSingleBeadSimulationChildrenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSingleBeadSimulationChildrenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSingleBeadSimulationChildrenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetSingleBeadSimulationChildrenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetSingleBeadSimulationChildrenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSingleBeadSimulationChildrenDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSingleBeadSimulationChildrenOK creates a GetSingleBeadSimulationChildrenOK with default headers values
func NewGetSingleBeadSimulationChildrenOK() *GetSingleBeadSimulationChildrenOK {
	return &GetSingleBeadSimulationChildrenOK{}
}

/*GetSingleBeadSimulationChildrenOK handles this case with default header values.

Successfully found the list of items
*/
type GetSingleBeadSimulationChildrenOK struct {
	/*Contains paging information in json format - totalCount, totalPages
	 */
	XPagination string

	Payload []*models.SingleBeadSimulation
}

func (o *GetSingleBeadSimulationChildrenOK) Error() string {
	return fmt.Sprintf("[GET /singlebeadsimulations/{id}/children][%d] getSingleBeadSimulationChildrenOK  %+v", 200, o.Payload)
}

func (o *GetSingleBeadSimulationChildrenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Pagination
	o.XPagination = response.GetHeader("X-Pagination")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSingleBeadSimulationChildrenUnauthorized creates a GetSingleBeadSimulationChildrenUnauthorized with default headers values
func NewGetSingleBeadSimulationChildrenUnauthorized() *GetSingleBeadSimulationChildrenUnauthorized {
	return &GetSingleBeadSimulationChildrenUnauthorized{}
}

/*GetSingleBeadSimulationChildrenUnauthorized handles this case with default header values.

Not authorized
*/
type GetSingleBeadSimulationChildrenUnauthorized struct {
	Payload *models.Error
}

func (o *GetSingleBeadSimulationChildrenUnauthorized) Error() string {
	return fmt.Sprintf("[GET /singlebeadsimulations/{id}/children][%d] getSingleBeadSimulationChildrenUnauthorized  %+v", 401, o.Payload)
}

func (o *GetSingleBeadSimulationChildrenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSingleBeadSimulationChildrenForbidden creates a GetSingleBeadSimulationChildrenForbidden with default headers values
func NewGetSingleBeadSimulationChildrenForbidden() *GetSingleBeadSimulationChildrenForbidden {
	return &GetSingleBeadSimulationChildrenForbidden{}
}

/*GetSingleBeadSimulationChildrenForbidden handles this case with default header values.

Forbidden
*/
type GetSingleBeadSimulationChildrenForbidden struct {
	Payload *models.Error
}

func (o *GetSingleBeadSimulationChildrenForbidden) Error() string {
	return fmt.Sprintf("[GET /singlebeadsimulations/{id}/children][%d] getSingleBeadSimulationChildrenForbidden  %+v", 403, o.Payload)
}

func (o *GetSingleBeadSimulationChildrenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSingleBeadSimulationChildrenDefault creates a GetSingleBeadSimulationChildrenDefault with default headers values
func NewGetSingleBeadSimulationChildrenDefault(code int) *GetSingleBeadSimulationChildrenDefault {
	return &GetSingleBeadSimulationChildrenDefault{
		_statusCode: code,
	}
}

/*GetSingleBeadSimulationChildrenDefault handles this case with default header values.

unexpected error
*/
type GetSingleBeadSimulationChildrenDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get single bead simulation children default response
func (o *GetSingleBeadSimulationChildrenDefault) Code() int {
	return o._statusCode
}

func (o *GetSingleBeadSimulationChildrenDefault) Error() string {
	return fmt.Sprintf("[GET /singlebeadsimulations/{id}/children][%d] getSingleBeadSimulationChildren default  %+v", o._statusCode, o.Payload)
}

func (o *GetSingleBeadSimulationChildrenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
