// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// GetPartSupportConfigurationReader is a Reader for the GetPartSupportConfiguration structure.
type GetPartSupportConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPartSupportConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPartSupportConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetPartSupportConfigurationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetPartSupportConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetPartSupportConfigurationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPartSupportConfigurationOK creates a GetPartSupportConfigurationOK with default headers values
func NewGetPartSupportConfigurationOK() *GetPartSupportConfigurationOK {
	return &GetPartSupportConfigurationOK{}
}

/*GetPartSupportConfigurationOK handles this case with default header values.

Successfully found a support configuration
*/
type GetPartSupportConfigurationOK struct {
	Payload *models.PartSupportConfiguration
}

func (o *GetPartSupportConfigurationOK) Error() string {
	return fmt.Sprintf("[GET /parts/{partId}/supportconfigurations/{supportConfigurationId}][%d] getPartSupportConfigurationOK  %+v", 200, o.Payload)
}

func (o *GetPartSupportConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PartSupportConfiguration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartSupportConfigurationForbidden creates a GetPartSupportConfigurationForbidden with default headers values
func NewGetPartSupportConfigurationForbidden() *GetPartSupportConfigurationForbidden {
	return &GetPartSupportConfigurationForbidden{}
}

/*GetPartSupportConfigurationForbidden handles this case with default header values.

Forbidden
*/
type GetPartSupportConfigurationForbidden struct {
	Payload *models.Error
}

func (o *GetPartSupportConfigurationForbidden) Error() string {
	return fmt.Sprintf("[GET /parts/{partId}/supportconfigurations/{supportConfigurationId}][%d] getPartSupportConfigurationForbidden  %+v", 403, o.Payload)
}

func (o *GetPartSupportConfigurationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPartSupportConfigurationNotFound creates a GetPartSupportConfigurationNotFound with default headers values
func NewGetPartSupportConfigurationNotFound() *GetPartSupportConfigurationNotFound {
	return &GetPartSupportConfigurationNotFound{}
}

/*GetPartSupportConfigurationNotFound handles this case with default header values.

Not found
*/
type GetPartSupportConfigurationNotFound struct {
}

func (o *GetPartSupportConfigurationNotFound) Error() string {
	return fmt.Sprintf("[GET /parts/{partId}/supportconfigurations/{supportConfigurationId}][%d] getPartSupportConfigurationNotFound ", 404)
}

func (o *GetPartSupportConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPartSupportConfigurationDefault creates a GetPartSupportConfigurationDefault with default headers values
func NewGetPartSupportConfigurationDefault(code int) *GetPartSupportConfigurationDefault {
	return &GetPartSupportConfigurationDefault{
		_statusCode: code,
	}
}

/*GetPartSupportConfigurationDefault handles this case with default header values.

unexpected error
*/
type GetPartSupportConfigurationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get part support configuration default response
func (o *GetPartSupportConfigurationDefault) Code() int {
	return o._statusCode
}

func (o *GetPartSupportConfigurationDefault) Error() string {
	return fmt.Sprintf("[GET /parts/{partId}/supportconfigurations/{supportConfigurationId}][%d] getPartSupportConfiguration default  %+v", o._statusCode, o.Payload)
}

func (o *GetPartSupportConfigurationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
