package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSimulationActivityParams creates a new GetSimulationActivityParams object
// with the default values initialized.
func NewGetSimulationActivityParams() *GetSimulationActivityParams {
	var ()
	return &GetSimulationActivityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSimulationActivityParamsWithTimeout creates a new GetSimulationActivityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSimulationActivityParamsWithTimeout(timeout time.Duration) *GetSimulationActivityParams {
	var ()
	return &GetSimulationActivityParams{

		timeout: timeout,
	}
}

// NewGetSimulationActivityParamsWithContext creates a new GetSimulationActivityParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSimulationActivityParamsWithContext(ctx context.Context) *GetSimulationActivityParams {
	var ()
	return &GetSimulationActivityParams{

		Context: ctx,
	}
}

// NewGetSimulationActivityParamsWithHTTPClient creates a new GetSimulationActivityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSimulationActivityParamsWithHTTPClient(client *http.Client) *GetSimulationActivityParams {
	var ()
	return &GetSimulationActivityParams{
		HTTPClient: client,
	}
}

/*GetSimulationActivityParams contains all the parameters to send to the API endpoint
for the get simulation activity operation typically these are written to a http.Request
*/
type GetSimulationActivityParams struct {

	/*ActivityID
	  activity identifier

	*/
	ActivityID int32
	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get simulation activity params
func (o *GetSimulationActivityParams) WithTimeout(timeout time.Duration) *GetSimulationActivityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get simulation activity params
func (o *GetSimulationActivityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get simulation activity params
func (o *GetSimulationActivityParams) WithContext(ctx context.Context) *GetSimulationActivityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get simulation activity params
func (o *GetSimulationActivityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get simulation activity params
func (o *GetSimulationActivityParams) WithHTTPClient(client *http.Client) *GetSimulationActivityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get simulation activity params
func (o *GetSimulationActivityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityID adds the activityID to the get simulation activity params
func (o *GetSimulationActivityParams) WithActivityID(activityID int32) *GetSimulationActivityParams {
	o.SetActivityID(activityID)
	return o
}

// SetActivityID adds the activityId to the get simulation activity params
func (o *GetSimulationActivityParams) SetActivityID(activityID int32) {
	o.ActivityID = activityID
}

// WithID adds the id to the get simulation activity params
func (o *GetSimulationActivityParams) WithID(id int32) *GetSimulationActivityParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get simulation activity params
func (o *GetSimulationActivityParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSimulationActivityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activityId
	if err := r.SetPathParam("activityId", swag.FormatInt32(o.ActivityID)); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
