// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// GetSimulationChildrenReader is a Reader for the GetSimulationChildren structure.
type GetSimulationChildrenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSimulationChildrenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSimulationChildrenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetSimulationChildrenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetSimulationChildrenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSimulationChildrenDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSimulationChildrenOK creates a GetSimulationChildrenOK with default headers values
func NewGetSimulationChildrenOK() *GetSimulationChildrenOK {
	return &GetSimulationChildrenOK{}
}

/*GetSimulationChildrenOK handles this case with default header values.

Successfully found the list of items
*/
type GetSimulationChildrenOK struct {
	/*Contains paging information in json format - totalCount, totalPages
	 */
	XPagination string

	Payload []*models.Simulation
}

func (o *GetSimulationChildrenOK) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/children][%d] getSimulationChildrenOK  %+v", 200, o.Payload)
}

func (o *GetSimulationChildrenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Pagination
	o.XPagination = response.GetHeader("X-Pagination")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSimulationChildrenUnauthorized creates a GetSimulationChildrenUnauthorized with default headers values
func NewGetSimulationChildrenUnauthorized() *GetSimulationChildrenUnauthorized {
	return &GetSimulationChildrenUnauthorized{}
}

/*GetSimulationChildrenUnauthorized handles this case with default header values.

Not authorized
*/
type GetSimulationChildrenUnauthorized struct {
	Payload *models.Error
}

func (o *GetSimulationChildrenUnauthorized) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/children][%d] getSimulationChildrenUnauthorized  %+v", 401, o.Payload)
}

func (o *GetSimulationChildrenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSimulationChildrenForbidden creates a GetSimulationChildrenForbidden with default headers values
func NewGetSimulationChildrenForbidden() *GetSimulationChildrenForbidden {
	return &GetSimulationChildrenForbidden{}
}

/*GetSimulationChildrenForbidden handles this case with default header values.

Forbidden
*/
type GetSimulationChildrenForbidden struct {
	Payload *models.Error
}

func (o *GetSimulationChildrenForbidden) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/children][%d] getSimulationChildrenForbidden  %+v", 403, o.Payload)
}

func (o *GetSimulationChildrenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSimulationChildrenDefault creates a GetSimulationChildrenDefault with default headers values
func NewGetSimulationChildrenDefault(code int) *GetSimulationChildrenDefault {
	return &GetSimulationChildrenDefault{
		_statusCode: code,
	}
}

/*GetSimulationChildrenDefault handles this case with default header values.

unexpected error
*/
type GetSimulationChildrenDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get simulation children default response
func (o *GetSimulationChildrenDefault) Code() int {
	return o._statusCode
}

func (o *GetSimulationChildrenDefault) Error() string {
	return fmt.Sprintf("[GET /simulations/{id}/children][%d] getSimulationChildren default  %+v", o._statusCode, o.Payload)
}

func (o *GetSimulationChildrenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
