// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMicrostructureSimulationParams creates a new GetMicrostructureSimulationParams object
// with the default values initialized.
func NewGetMicrostructureSimulationParams() *GetMicrostructureSimulationParams {
	var ()
	return &GetMicrostructureSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMicrostructureSimulationParamsWithTimeout creates a new GetMicrostructureSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMicrostructureSimulationParamsWithTimeout(timeout time.Duration) *GetMicrostructureSimulationParams {
	var ()
	return &GetMicrostructureSimulationParams{

		timeout: timeout,
	}
}

// NewGetMicrostructureSimulationParamsWithContext creates a new GetMicrostructureSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMicrostructureSimulationParamsWithContext(ctx context.Context) *GetMicrostructureSimulationParams {
	var ()
	return &GetMicrostructureSimulationParams{

		Context: ctx,
	}
}

// NewGetMicrostructureSimulationParamsWithHTTPClient creates a new GetMicrostructureSimulationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMicrostructureSimulationParamsWithHTTPClient(client *http.Client) *GetMicrostructureSimulationParams {
	var ()
	return &GetMicrostructureSimulationParams{
		HTTPClient: client,
	}
}

/*GetMicrostructureSimulationParams contains all the parameters to send to the API endpoint
for the get microstructure simulation operation typically these are written to a http.Request
*/
type GetMicrostructureSimulationParams struct {

	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) WithTimeout(timeout time.Duration) *GetMicrostructureSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) WithContext(ctx context.Context) *GetMicrostructureSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) WithHTTPClient(client *http.Client) *GetMicrostructureSimulationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) WithID(id int32) *GetMicrostructureSimulationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get microstructure simulation params
func (o *GetMicrostructureSimulationParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMicrostructureSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
