// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBuildFileParams creates a new GetBuildFileParams object
// with the default values initialized.
func NewGetBuildFileParams() *GetBuildFileParams {
	var ()
	return &GetBuildFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBuildFileParamsWithTimeout creates a new GetBuildFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBuildFileParamsWithTimeout(timeout time.Duration) *GetBuildFileParams {
	var ()
	return &GetBuildFileParams{

		timeout: timeout,
	}
}

// NewGetBuildFileParamsWithContext creates a new GetBuildFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBuildFileParamsWithContext(ctx context.Context) *GetBuildFileParams {
	var ()
	return &GetBuildFileParams{

		Context: ctx,
	}
}

// NewGetBuildFileParamsWithHTTPClient creates a new GetBuildFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBuildFileParamsWithHTTPClient(client *http.Client) *GetBuildFileParams {
	var ()
	return &GetBuildFileParams{
		HTTPClient: client,
	}
}

/*GetBuildFileParams contains all the parameters to send to the API endpoint
for the get build file operation typically these are written to a http.Request
*/
type GetBuildFileParams struct {

	/*ID
	  ID of build file to retrieve

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get build file params
func (o *GetBuildFileParams) WithTimeout(timeout time.Duration) *GetBuildFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get build file params
func (o *GetBuildFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get build file params
func (o *GetBuildFileParams) WithContext(ctx context.Context) *GetBuildFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get build file params
func (o *GetBuildFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get build file params
func (o *GetBuildFileParams) WithHTTPClient(client *http.Client) *GetBuildFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get build file params
func (o *GetBuildFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get build file params
func (o *GetBuildFileParams) WithID(id int32) *GetBuildFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get build file params
func (o *GetBuildFileParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBuildFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
