// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPartSupportByIDParams creates a new GetPartSupportByIDParams object
// with the default values initialized.
func NewGetPartSupportByIDParams() *GetPartSupportByIDParams {
	var ()
	return &GetPartSupportByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPartSupportByIDParamsWithTimeout creates a new GetPartSupportByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPartSupportByIDParamsWithTimeout(timeout time.Duration) *GetPartSupportByIDParams {
	var ()
	return &GetPartSupportByIDParams{

		timeout: timeout,
	}
}

// NewGetPartSupportByIDParamsWithContext creates a new GetPartSupportByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPartSupportByIDParamsWithContext(ctx context.Context) *GetPartSupportByIDParams {
	var ()
	return &GetPartSupportByIDParams{

		Context: ctx,
	}
}

// NewGetPartSupportByIDParamsWithHTTPClient creates a new GetPartSupportByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPartSupportByIDParamsWithHTTPClient(client *http.Client) *GetPartSupportByIDParams {
	var ()
	return &GetPartSupportByIDParams{
		HTTPClient: client,
	}
}

/*GetPartSupportByIDParams contains all the parameters to send to the API endpoint
for the get part support by Id operation typically these are written to a http.Request
*/
type GetPartSupportByIDParams struct {

	/*ID
	  ID of support to get

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get part support by Id params
func (o *GetPartSupportByIDParams) WithTimeout(timeout time.Duration) *GetPartSupportByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get part support by Id params
func (o *GetPartSupportByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get part support by Id params
func (o *GetPartSupportByIDParams) WithContext(ctx context.Context) *GetPartSupportByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get part support by Id params
func (o *GetPartSupportByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get part support by Id params
func (o *GetPartSupportByIDParams) WithHTTPClient(client *http.Client) *GetPartSupportByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get part support by Id params
func (o *GetPartSupportByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get part support by Id params
func (o *GetPartSupportByIDParams) WithID(id int32) *GetPartSupportByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get part support by Id params
func (o *GetPartSupportByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPartSupportByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
