// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewPostSingleBeadSimulationParams creates a new PostSingleBeadSimulationParams object
// with the default values initialized.
func NewPostSingleBeadSimulationParams() *PostSingleBeadSimulationParams {
	var ()
	return &PostSingleBeadSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSingleBeadSimulationParamsWithTimeout creates a new PostSingleBeadSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSingleBeadSimulationParamsWithTimeout(timeout time.Duration) *PostSingleBeadSimulationParams {
	var ()
	return &PostSingleBeadSimulationParams{

		timeout: timeout,
	}
}

// NewPostSingleBeadSimulationParamsWithContext creates a new PostSingleBeadSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSingleBeadSimulationParamsWithContext(ctx context.Context) *PostSingleBeadSimulationParams {
	var ()
	return &PostSingleBeadSimulationParams{

		Context: ctx,
	}
}

// NewPostSingleBeadSimulationParamsWithHTTPClient creates a new PostSingleBeadSimulationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSingleBeadSimulationParamsWithHTTPClient(client *http.Client) *PostSingleBeadSimulationParams {
	var ()
	return &PostSingleBeadSimulationParams{
		HTTPClient: client,
	}
}

/*PostSingleBeadSimulationParams contains all the parameters to send to the API endpoint
for the post single bead simulation operation typically these are written to a http.Request
*/
type PostSingleBeadSimulationParams struct {

	/*SingleBeadSimulation
	  SingleBeadSimulation fields required to add the simulation

	*/
	SingleBeadSimulation *models.SingleBeadSimulation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) WithTimeout(timeout time.Duration) *PostSingleBeadSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) WithContext(ctx context.Context) *PostSingleBeadSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) WithHTTPClient(client *http.Client) *PostSingleBeadSimulationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSingleBeadSimulation adds the singleBeadSimulation to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) WithSingleBeadSimulation(singleBeadSimulation *models.SingleBeadSimulation) *PostSingleBeadSimulationParams {
	o.SetSingleBeadSimulation(singleBeadSimulation)
	return o
}

// SetSingleBeadSimulation adds the singleBeadSimulation to the post single bead simulation params
func (o *PostSingleBeadSimulationParams) SetSingleBeadSimulation(singleBeadSimulation *models.SingleBeadSimulation) {
	o.SingleBeadSimulation = singleBeadSimulation
}

// WriteToRequest writes these params to a swagger request
func (o *PostSingleBeadSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SingleBeadSimulation != nil {
		if err := r.SetBodyParam(o.SingleBeadSimulation); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
