// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewPostBuildFileParams creates a new PostBuildFileParams object
// with the default values initialized.
func NewPostBuildFileParams() *PostBuildFileParams {
	var ()
	return &PostBuildFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostBuildFileParamsWithTimeout creates a new PostBuildFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostBuildFileParamsWithTimeout(timeout time.Duration) *PostBuildFileParams {
	var ()
	return &PostBuildFileParams{

		timeout: timeout,
	}
}

// NewPostBuildFileParamsWithContext creates a new PostBuildFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostBuildFileParamsWithContext(ctx context.Context) *PostBuildFileParams {
	var ()
	return &PostBuildFileParams{

		Context: ctx,
	}
}

// NewPostBuildFileParamsWithHTTPClient creates a new PostBuildFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostBuildFileParamsWithHTTPClient(client *http.Client) *PostBuildFileParams {
	var ()
	return &PostBuildFileParams{
		HTTPClient: client,
	}
}

/*PostBuildFileParams contains all the parameters to send to the API endpoint
for the post build file operation typically these are written to a http.Request
*/
type PostBuildFileParams struct {

	/*BuildFilePost
	  build file to add

	*/
	BuildFilePost *models.BuildFilePost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post build file params
func (o *PostBuildFileParams) WithTimeout(timeout time.Duration) *PostBuildFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post build file params
func (o *PostBuildFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post build file params
func (o *PostBuildFileParams) WithContext(ctx context.Context) *PostBuildFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post build file params
func (o *PostBuildFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post build file params
func (o *PostBuildFileParams) WithHTTPClient(client *http.Client) *PostBuildFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post build file params
func (o *PostBuildFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildFilePost adds the buildFilePost to the post build file params
func (o *PostBuildFileParams) WithBuildFilePost(buildFilePost *models.BuildFilePost) *PostBuildFileParams {
	o.SetBuildFilePost(buildFilePost)
	return o
}

// SetBuildFilePost adds the buildFilePost to the post build file params
func (o *PostBuildFileParams) SetBuildFilePost(buildFilePost *models.BuildFilePost) {
	o.BuildFilePost = buildFilePost
}

// WriteToRequest writes these params to a swagger request
func (o *PostBuildFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BuildFilePost == nil {
		o.BuildFilePost = new(models.BuildFilePost)
	}

	if err := r.SetBodyParam(o.BuildFilePost); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
