// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewPostSimulationActivityParams creates a new PostSimulationActivityParams object
// with the default values initialized.
func NewPostSimulationActivityParams() *PostSimulationActivityParams {
	var ()
	return &PostSimulationActivityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSimulationActivityParamsWithTimeout creates a new PostSimulationActivityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSimulationActivityParamsWithTimeout(timeout time.Duration) *PostSimulationActivityParams {
	var ()
	return &PostSimulationActivityParams{

		timeout: timeout,
	}
}

// NewPostSimulationActivityParamsWithContext creates a new PostSimulationActivityParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSimulationActivityParamsWithContext(ctx context.Context) *PostSimulationActivityParams {
	var ()
	return &PostSimulationActivityParams{

		Context: ctx,
	}
}

// NewPostSimulationActivityParamsWithHTTPClient creates a new PostSimulationActivityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSimulationActivityParamsWithHTTPClient(client *http.Client) *PostSimulationActivityParams {
	var ()
	return &PostSimulationActivityParams{
		HTTPClient: client,
	}
}

/*PostSimulationActivityParams contains all the parameters to send to the API endpoint
for the post simulation activity operation typically these are written to a http.Request
*/
type PostSimulationActivityParams struct {

	/*SimulationActivity
	  An activity for a simulation.  An activity represents the execution of a worker in the simulation pipeline.

	*/
	SimulationActivity *models.SimulationActivity
	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post simulation activity params
func (o *PostSimulationActivityParams) WithTimeout(timeout time.Duration) *PostSimulationActivityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post simulation activity params
func (o *PostSimulationActivityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post simulation activity params
func (o *PostSimulationActivityParams) WithContext(ctx context.Context) *PostSimulationActivityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post simulation activity params
func (o *PostSimulationActivityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post simulation activity params
func (o *PostSimulationActivityParams) WithHTTPClient(client *http.Client) *PostSimulationActivityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post simulation activity params
func (o *PostSimulationActivityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSimulationActivity adds the simulationActivity to the post simulation activity params
func (o *PostSimulationActivityParams) WithSimulationActivity(simulationActivity *models.SimulationActivity) *PostSimulationActivityParams {
	o.SetSimulationActivity(simulationActivity)
	return o
}

// SetSimulationActivity adds the simulationActivity to the post simulation activity params
func (o *PostSimulationActivityParams) SetSimulationActivity(simulationActivity *models.SimulationActivity) {
	o.SimulationActivity = simulationActivity
}

// WithID adds the id to the post simulation activity params
func (o *PostSimulationActivityParams) WithID(id int32) *PostSimulationActivityParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post simulation activity params
func (o *PostSimulationActivityParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostSimulationActivityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SimulationActivity != nil {
		if err := r.SetBodyParam(o.SimulationActivity); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
