// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewPostMachineParams creates a new PostMachineParams object
// with the default values initialized.
func NewPostMachineParams() *PostMachineParams {
	var ()
	return &PostMachineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMachineParamsWithTimeout creates a new PostMachineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMachineParamsWithTimeout(timeout time.Duration) *PostMachineParams {
	var ()
	return &PostMachineParams{

		timeout: timeout,
	}
}

// NewPostMachineParamsWithContext creates a new PostMachineParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMachineParamsWithContext(ctx context.Context) *PostMachineParams {
	var ()
	return &PostMachineParams{

		Context: ctx,
	}
}

// NewPostMachineParamsWithHTTPClient creates a new PostMachineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMachineParamsWithHTTPClient(client *http.Client) *PostMachineParams {
	var ()
	return &PostMachineParams{
		HTTPClient: client,
	}
}

/*PostMachineParams contains all the parameters to send to the API endpoint
for the post machine operation typically these are written to a http.Request
*/
type PostMachineParams struct {

	/*Machine*/
	Machine *models.Machine

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post machine params
func (o *PostMachineParams) WithTimeout(timeout time.Duration) *PostMachineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post machine params
func (o *PostMachineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post machine params
func (o *PostMachineParams) WithContext(ctx context.Context) *PostMachineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post machine params
func (o *PostMachineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post machine params
func (o *PostMachineParams) WithHTTPClient(client *http.Client) *PostMachineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post machine params
func (o *PostMachineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMachine adds the machine to the post machine params
func (o *PostMachineParams) WithMachine(machine *models.Machine) *PostMachineParams {
	o.SetMachine(machine)
	return o
}

// SetMachine adds the machine to the post machine params
func (o *PostMachineParams) SetMachine(machine *models.Machine) {
	o.Machine = machine
}

// WriteToRequest writes these params to a swagger request
func (o *PostMachineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Machine != nil {
		if err := r.SetBodyParam(o.Machine); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
