// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewPutMachineParams creates a new PutMachineParams object
// with the default values initialized.
func NewPutMachineParams() *PutMachineParams {
	var ()
	return &PutMachineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutMachineParamsWithTimeout creates a new PutMachineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutMachineParamsWithTimeout(timeout time.Duration) *PutMachineParams {
	var ()
	return &PutMachineParams{

		timeout: timeout,
	}
}

// NewPutMachineParamsWithContext creates a new PutMachineParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutMachineParamsWithContext(ctx context.Context) *PutMachineParams {
	var ()
	return &PutMachineParams{

		Context: ctx,
	}
}

// NewPutMachineParamsWithHTTPClient creates a new PutMachineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutMachineParamsWithHTTPClient(client *http.Client) *PutMachineParams {
	var ()
	return &PutMachineParams{
		HTTPClient: client,
	}
}

/*PutMachineParams contains all the parameters to send to the API endpoint
for the put machine operation typically these are written to a http.Request
*/
type PutMachineParams struct {

	/*ID
	  machine identifier

	*/
	ID int32
	/*Machine*/
	Machine *models.Machine

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put machine params
func (o *PutMachineParams) WithTimeout(timeout time.Duration) *PutMachineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put machine params
func (o *PutMachineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put machine params
func (o *PutMachineParams) WithContext(ctx context.Context) *PutMachineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put machine params
func (o *PutMachineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put machine params
func (o *PutMachineParams) WithHTTPClient(client *http.Client) *PutMachineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put machine params
func (o *PutMachineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put machine params
func (o *PutMachineParams) WithID(id int32) *PutMachineParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put machine params
func (o *PutMachineParams) SetID(id int32) {
	o.ID = id
}

// WithMachine adds the machine to the put machine params
func (o *PutMachineParams) WithMachine(machine *models.Machine) *PutMachineParams {
	o.SetMachine(machine)
	return o
}

// SetMachine adds the machine to the put machine params
func (o *PutMachineParams) SetMachine(machine *models.Machine) {
	o.Machine = machine
}

// WriteToRequest writes these params to a swagger request
func (o *PutMachineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Machine != nil {
		if err := r.SetBodyParam(o.Machine); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
