// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// NewUpdateBuildFileParams creates a new UpdateBuildFileParams object
// with the default values initialized.
func NewUpdateBuildFileParams() *UpdateBuildFileParams {
	var ()
	return &UpdateBuildFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBuildFileParamsWithTimeout creates a new UpdateBuildFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateBuildFileParamsWithTimeout(timeout time.Duration) *UpdateBuildFileParams {
	var ()
	return &UpdateBuildFileParams{

		timeout: timeout,
	}
}

// NewUpdateBuildFileParamsWithContext creates a new UpdateBuildFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateBuildFileParamsWithContext(ctx context.Context) *UpdateBuildFileParams {
	var ()
	return &UpdateBuildFileParams{

		Context: ctx,
	}
}

// NewUpdateBuildFileParamsWithHTTPClient creates a new UpdateBuildFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateBuildFileParamsWithHTTPClient(client *http.Client) *UpdateBuildFileParams {
	var ()
	return &UpdateBuildFileParams{
		HTTPClient: client,
	}
}

/*UpdateBuildFileParams contains all the parameters to send to the API endpoint
for the update build file operation typically these are written to a http.Request
*/
type UpdateBuildFileParams struct {

	/*BuildFile
	  build file to update

	*/
	BuildFile *models.BuildFile
	/*ID
	  ID of build file to update

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update build file params
func (o *UpdateBuildFileParams) WithTimeout(timeout time.Duration) *UpdateBuildFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update build file params
func (o *UpdateBuildFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update build file params
func (o *UpdateBuildFileParams) WithContext(ctx context.Context) *UpdateBuildFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update build file params
func (o *UpdateBuildFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update build file params
func (o *UpdateBuildFileParams) WithHTTPClient(client *http.Client) *UpdateBuildFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update build file params
func (o *UpdateBuildFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildFile adds the buildFile to the update build file params
func (o *UpdateBuildFileParams) WithBuildFile(buildFile *models.BuildFile) *UpdateBuildFileParams {
	o.SetBuildFile(buildFile)
	return o
}

// SetBuildFile adds the buildFile to the update build file params
func (o *UpdateBuildFileParams) SetBuildFile(buildFile *models.BuildFile) {
	o.BuildFile = buildFile
}

// WithID adds the id to the update build file params
func (o *UpdateBuildFileParams) WithID(id int32) *UpdateBuildFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update build file params
func (o *UpdateBuildFileParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBuildFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BuildFile != nil {
		if err := r.SetBodyParam(o.BuildFile); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
