package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSimulationsParams creates a new GetSimulationsParams object
// with the default values initialized.
func NewGetSimulationsParams() *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSimulationsParamsWithTimeout creates a new GetSimulationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSimulationsParamsWithTimeout(timeout time.Duration) *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{

		timeout: timeout,
	}
}

// NewGetSimulationsParamsWithContext creates a new GetSimulationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSimulationsParamsWithContext(ctx context.Context) *GetSimulationsParams {
	var ()
	return &GetSimulationsParams{

		Context: ctx,
	}
}

/*GetSimulationsParams contains all the parameters to send to the API endpoint
for the get simulations operation typically these are written to a http.Request
*/
type GetSimulationsParams struct {

	/*Limit
	  number of materials to return within the query

	*/
	Limit *int32
	/*Offset
	  starting paging count; ex. offset of 60 will skip the first 60 items in the list

	*/
	Offset *int32
	/*OrganizationID
	  the organization id to get items for.  Must be provided as API callers only have access to items belonging to their organization.

	*/
	OrganizationID int32
	/*Sort
	  key:direction pairs for one or multiple field sort orders

	*/
	Sort []string
	/*Status
	  simulation status for items retreived. Multiple status values may be specified e.g. "status=completed&status=error&status=cancelled"

	*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get simulations params
func (o *GetSimulationsParams) WithTimeout(timeout time.Duration) *GetSimulationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get simulations params
func (o *GetSimulationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get simulations params
func (o *GetSimulationsParams) WithContext(ctx context.Context) *GetSimulationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get simulations params
func (o *GetSimulationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithLimit adds the limit to the get simulations params
func (o *GetSimulationsParams) WithLimit(limit *int32) *GetSimulationsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get simulations params
func (o *GetSimulationsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get simulations params
func (o *GetSimulationsParams) WithOffset(offset *int32) *GetSimulationsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get simulations params
func (o *GetSimulationsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the get simulations params
func (o *GetSimulationsParams) WithOrganizationID(organizationID int32) *GetSimulationsParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get simulations params
func (o *GetSimulationsParams) SetOrganizationID(organizationID int32) {
	o.OrganizationID = organizationID
}

// WithSort adds the sort to the get simulations params
func (o *GetSimulationsParams) WithSort(sort []string) *GetSimulationsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get simulations params
func (o *GetSimulationsParams) SetSort(sort []string) {
	o.Sort = sort
}

// WithStatus adds the status to the get simulations params
func (o *GetSimulationsParams) WithStatus(status *string) *GetSimulationsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get simulations params
func (o *GetSimulationsParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *GetSimulationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	// query param organizationId
	qrOrganizationID := o.OrganizationID
	qOrganizationID := swag.FormatInt32(qrOrganizationID)
	if qOrganizationID != "" {
		if err := r.SetQueryParam("organizationId", qOrganizationID); err != nil {
			return err
		}
	}

	valuesSort := o.Sort

	joinedSort := swag.JoinByFormat(valuesSort, "csv")
	// query array param sort
	if err := r.SetQueryParam("sort", joinedSort...); err != nil {
		return err
	}

	if o.Status != nil {

		// query param status
		var qrStatus string
		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {
			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
