package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// GetAssumedStrainSimulationReader is a Reader for the GetAssumedStrainSimulation structure.
type GetAssumedStrainSimulationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssumedStrainSimulationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAssumedStrainSimulationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetAssumedStrainSimulationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAssumedStrainSimulationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAssumedStrainSimulationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAssumedStrainSimulationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAssumedStrainSimulationOK creates a GetAssumedStrainSimulationOK with default headers values
func NewGetAssumedStrainSimulationOK() *GetAssumedStrainSimulationOK {
	return &GetAssumedStrainSimulationOK{}
}

/*GetAssumedStrainSimulationOK handles this case with default header values.

Successfully retrieved simulation
*/
type GetAssumedStrainSimulationOK struct {
	Payload *models.AssumedStrainSimulation
}

func (o *GetAssumedStrainSimulationOK) Error() string {
	return fmt.Sprintf("[GET /assumedstrainsimulations/{id}][%d] getAssumedStrainSimulationOK  %+v", 200, o.Payload)
}

func (o *GetAssumedStrainSimulationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssumedStrainSimulation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssumedStrainSimulationUnauthorized creates a GetAssumedStrainSimulationUnauthorized with default headers values
func NewGetAssumedStrainSimulationUnauthorized() *GetAssumedStrainSimulationUnauthorized {
	return &GetAssumedStrainSimulationUnauthorized{}
}

/*GetAssumedStrainSimulationUnauthorized handles this case with default header values.

Not authorized
*/
type GetAssumedStrainSimulationUnauthorized struct {
	Payload *models.Error
}

func (o *GetAssumedStrainSimulationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /assumedstrainsimulations/{id}][%d] getAssumedStrainSimulationUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAssumedStrainSimulationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssumedStrainSimulationForbidden creates a GetAssumedStrainSimulationForbidden with default headers values
func NewGetAssumedStrainSimulationForbidden() *GetAssumedStrainSimulationForbidden {
	return &GetAssumedStrainSimulationForbidden{}
}

/*GetAssumedStrainSimulationForbidden handles this case with default header values.

Forbidden
*/
type GetAssumedStrainSimulationForbidden struct {
	Payload *models.Error
}

func (o *GetAssumedStrainSimulationForbidden) Error() string {
	return fmt.Sprintf("[GET /assumedstrainsimulations/{id}][%d] getAssumedStrainSimulationForbidden  %+v", 403, o.Payload)
}

func (o *GetAssumedStrainSimulationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssumedStrainSimulationNotFound creates a GetAssumedStrainSimulationNotFound with default headers values
func NewGetAssumedStrainSimulationNotFound() *GetAssumedStrainSimulationNotFound {
	return &GetAssumedStrainSimulationNotFound{}
}

/*GetAssumedStrainSimulationNotFound handles this case with default header values.

Simulation not found (id invalid)
*/
type GetAssumedStrainSimulationNotFound struct {
	Payload *models.Error
}

func (o *GetAssumedStrainSimulationNotFound) Error() string {
	return fmt.Sprintf("[GET /assumedstrainsimulations/{id}][%d] getAssumedStrainSimulationNotFound  %+v", 404, o.Payload)
}

func (o *GetAssumedStrainSimulationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAssumedStrainSimulationDefault creates a GetAssumedStrainSimulationDefault with default headers values
func NewGetAssumedStrainSimulationDefault(code int) *GetAssumedStrainSimulationDefault {
	return &GetAssumedStrainSimulationDefault{
		_statusCode: code,
	}
}

/*GetAssumedStrainSimulationDefault handles this case with default header values.

unexpected error
*/
type GetAssumedStrainSimulationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get assumed strain simulation default response
func (o *GetAssumedStrainSimulationDefault) Code() int {
	return o._statusCode
}

func (o *GetAssumedStrainSimulationDefault) Error() string {
	return fmt.Sprintf("[GET /assumedstrainsimulations/{id}][%d] getAssumedStrainSimulation default  %+v", o._statusCode, o.Payload)
}

func (o *GetAssumedStrainSimulationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
