package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetThermalSimulationParams creates a new GetThermalSimulationParams object
// with the default values initialized.
func NewGetThermalSimulationParams() *GetThermalSimulationParams {
	var ()
	return &GetThermalSimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetThermalSimulationParamsWithTimeout creates a new GetThermalSimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetThermalSimulationParamsWithTimeout(timeout time.Duration) *GetThermalSimulationParams {
	var ()
	return &GetThermalSimulationParams{

		timeout: timeout,
	}
}

// NewGetThermalSimulationParamsWithContext creates a new GetThermalSimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetThermalSimulationParamsWithContext(ctx context.Context) *GetThermalSimulationParams {
	var ()
	return &GetThermalSimulationParams{

		Context: ctx,
	}
}

/*GetThermalSimulationParams contains all the parameters to send to the API endpoint
for the get thermal simulation operation typically these are written to a http.Request
*/
type GetThermalSimulationParams struct {

	/*ID
	  simulation identifier

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get thermal simulation params
func (o *GetThermalSimulationParams) WithTimeout(timeout time.Duration) *GetThermalSimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get thermal simulation params
func (o *GetThermalSimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get thermal simulation params
func (o *GetThermalSimulationParams) WithContext(ctx context.Context) *GetThermalSimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get thermal simulation params
func (o *GetThermalSimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the get thermal simulation params
func (o *GetThermalSimulationParams) WithID(id int64) *GetThermalSimulationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get thermal simulation params
func (o *GetThermalSimulationParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetThermalSimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
