package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/simulation-goclient/models"
)

// PostAssumedStrainSimulationReader is a Reader for the PostAssumedStrainSimulation structure.
type PostAssumedStrainSimulationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAssumedStrainSimulationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAssumedStrainSimulationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostAssumedStrainSimulationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostAssumedStrainSimulationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostAssumedStrainSimulationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostAssumedStrainSimulationOK creates a PostAssumedStrainSimulationOK with default headers values
func NewPostAssumedStrainSimulationOK() *PostAssumedStrainSimulationOK {
	return &PostAssumedStrainSimulationOK{}
}

/*PostAssumedStrainSimulationOK handles this case with default header values.

Successfully added a simulation
*/
type PostAssumedStrainSimulationOK struct {
	Payload *models.AssumedStrainSimulation
}

func (o *PostAssumedStrainSimulationOK) Error() string {
	return fmt.Sprintf("[POST /assumedstrainsimulations][%d] postAssumedStrainSimulationOK  %+v", 200, o.Payload)
}

func (o *PostAssumedStrainSimulationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssumedStrainSimulation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAssumedStrainSimulationUnauthorized creates a PostAssumedStrainSimulationUnauthorized with default headers values
func NewPostAssumedStrainSimulationUnauthorized() *PostAssumedStrainSimulationUnauthorized {
	return &PostAssumedStrainSimulationUnauthorized{}
}

/*PostAssumedStrainSimulationUnauthorized handles this case with default header values.

Not authorized
*/
type PostAssumedStrainSimulationUnauthorized struct {
	Payload *models.Error
}

func (o *PostAssumedStrainSimulationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /assumedstrainsimulations][%d] postAssumedStrainSimulationUnauthorized  %+v", 401, o.Payload)
}

func (o *PostAssumedStrainSimulationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAssumedStrainSimulationForbidden creates a PostAssumedStrainSimulationForbidden with default headers values
func NewPostAssumedStrainSimulationForbidden() *PostAssumedStrainSimulationForbidden {
	return &PostAssumedStrainSimulationForbidden{}
}

/*PostAssumedStrainSimulationForbidden handles this case with default header values.

Forbidden
*/
type PostAssumedStrainSimulationForbidden struct {
	Payload *models.Error
}

func (o *PostAssumedStrainSimulationForbidden) Error() string {
	return fmt.Sprintf("[POST /assumedstrainsimulations][%d] postAssumedStrainSimulationForbidden  %+v", 403, o.Payload)
}

func (o *PostAssumedStrainSimulationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAssumedStrainSimulationDefault creates a PostAssumedStrainSimulationDefault with default headers values
func NewPostAssumedStrainSimulationDefault(code int) *PostAssumedStrainSimulationDefault {
	return &PostAssumedStrainSimulationDefault{
		_statusCode: code,
	}
}

/*PostAssumedStrainSimulationDefault handles this case with default header values.

unexpected error
*/
type PostAssumedStrainSimulationDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post assumed strain simulation default response
func (o *PostAssumedStrainSimulationDefault) Code() int {
	return o._statusCode
}

func (o *PostAssumedStrainSimulationDefault) Error() string {
	return fmt.Sprintf("[POST /assumedstrainsimulations][%d] postAssumedStrainSimulation default  %+v", o._statusCode, o.Payload)
}

func (o *PostAssumedStrainSimulationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
