package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStartPorositySimulationParams creates a new StartPorositySimulationParams object
// with the default values initialized.
func NewStartPorositySimulationParams() *StartPorositySimulationParams {
	var ()
	return &StartPorositySimulationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartPorositySimulationParamsWithTimeout creates a new StartPorositySimulationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartPorositySimulationParamsWithTimeout(timeout time.Duration) *StartPorositySimulationParams {
	var ()
	return &StartPorositySimulationParams{

		timeout: timeout,
	}
}

// NewStartPorositySimulationParamsWithContext creates a new StartPorositySimulationParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartPorositySimulationParamsWithContext(ctx context.Context) *StartPorositySimulationParams {
	var ()
	return &StartPorositySimulationParams{

		Context: ctx,
	}
}

/*StartPorositySimulationParams contains all the parameters to send to the API endpoint
for the start porosity simulation operation typically these are written to a http.Request
*/
type StartPorositySimulationParams struct {

	/*ID
	  simulation identifier

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start porosity simulation params
func (o *StartPorositySimulationParams) WithTimeout(timeout time.Duration) *StartPorositySimulationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start porosity simulation params
func (o *StartPorositySimulationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start porosity simulation params
func (o *StartPorositySimulationParams) WithContext(ctx context.Context) *StartPorositySimulationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start porosity simulation params
func (o *StartPorositySimulationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the start porosity simulation params
func (o *StartPorositySimulationParams) WithID(id int32) *StartPorositySimulationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the start porosity simulation params
func (o *StartPorositySimulationParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StartPorositySimulationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
