// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Machine machine
// swagger:model Machine
type Machine struct {

	// false if not archived, true if archived
	// Required: true
	Archived *bool `json:"archived"`

	// configuration
	Configuration *MachineConfiguration `json:"configuration,omitempty"`

	// configuration history
	ConfigurationHistory MachineConfigurationHistory `json:"configurationHistory"`

	// identifier for the active configuration for the machine
	// Required: true
	ConfigurationID *int32 `json:"configurationId"`

	// created time stamp, set server-side, read only field
	// Required: true
	Created *strfmt.DateTime `json:"created"`

	// creating user, set server-side, read only field
	// Required: true
	CreatedBy *string `json:"createdBy"`

	// machine description
	// Max Length: 2048
	Description string `json:"description,omitempty"`

	// machine identifier
	// Required: true
	ID *int32 `json:"id"`

	// flag whether it is a core machine or a custom machine
	// Required: true
	IsCore *bool `json:"isCore"`

	// key associated with this machine
	// Required: true
	// Max Length: 16
	Key *string `json:"key"`

	// last modified time stamp, set server-side, read only field
	// Required: true
	LastModified *strfmt.DateTime `json:"lastModified"`

	// modifying user, set server-side, read only field
	// Required: true
	LastModifiedBy *string `json:"lastModifiedBy"`

	// machine name
	// Required: true
	// Max Length: 128
	Name *string `json:"name"`

	// organization identifier
	// Required: true
	OrganizationID *int32 `json:"organizationId"`
}

// Validate validates this machine
func (m *Machine) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArchived(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateConfiguration(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateConfigurationID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCreatedBy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIsCore(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLastModified(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLastModifiedBy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOrganizationID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Machine) validateArchived(formats strfmt.Registry) error {

	if err := validate.Required("archived", "body", m.Archived); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateConfiguration(formats strfmt.Registry) error {

	if swag.IsZero(m.Configuration) { // not required
		return nil
	}

	if m.Configuration != nil {

		if err := m.Configuration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configuration")
			}
			return err
		}
	}

	return nil
}

func (m *Machine) validateConfigurationID(formats strfmt.Registry) error {

	if err := validate.Required("configurationId", "body", m.ConfigurationID); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", m.Created); err != nil {
		return err
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateCreatedBy(formats strfmt.Registry) error {

	if err := validate.Required("createdBy", "body", m.CreatedBy); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", string(m.Description), 2048); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateIsCore(formats strfmt.Registry) error {

	if err := validate.Required("isCore", "body", m.IsCore); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	if err := validate.MaxLength("key", "body", string(*m.Key), 16); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateLastModified(formats strfmt.Registry) error {

	if err := validate.Required("lastModified", "body", m.LastModified); err != nil {
		return err
	}

	if err := validate.FormatOf("lastModified", "body", "date-time", m.LastModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateLastModifiedBy(formats strfmt.Registry) error {

	if err := validate.Required("lastModifiedBy", "body", m.LastModifiedBy); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(*m.Name), 128); err != nil {
		return err
	}

	return nil
}

func (m *Machine) validateOrganizationID(formats strfmt.Registry) error {

	if err := validate.Required("organizationId", "body", m.OrganizationID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Machine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Machine) UnmarshalBinary(b []byte) error {
	var res Machine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
