// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PartSupportPost part support post
// swagger:model PartSupportPost
type PartSupportPost struct {

	// Free form description of the support, max 2048 characters
	Description string `json:"description,omitempty"`

	// Remote s3 key of a newly uploaded stl file.  Use parts/:partId/supports/geometryurl endpoint to upload the support before calling POST.  Max length 256 characters.
	// Required: true
	FileLocation *string `json:"fileLocation"`

	// Name of the support, max 50 characters
	// Required: true
	Name *string `json:"name"`

	// Original support file name, max 248 characters
	// Required: true
	OriginalFileName *string `json:"originalFileName"`

	// Id of the part that owns this support record
	// Required: true
	PartID *int32 `json:"partId"`
}

// Validate validates this part support post
func (m *PartSupportPost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFileLocation(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOriginalFileName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePartID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartSupportPost) validateFileLocation(formats strfmt.Registry) error {

	if err := validate.Required("fileLocation", "body", m.FileLocation); err != nil {
		return err
	}

	return nil
}

func (m *PartSupportPost) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *PartSupportPost) validateOriginalFileName(formats strfmt.Registry) error {

	if err := validate.Required("originalFileName", "body", m.OriginalFileName); err != nil {
		return err
	}

	return nil
}

func (m *PartSupportPost) validatePartID(formats strfmt.Registry) error {

	if err := validate.Required("partId", "body", m.PartID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PartSupportPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartSupportPost) UnmarshalBinary(b []byte) error {
	var res PartSupportPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
