package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// SimulationLog simulation log
// swagger:model SimulationLog
type SimulationLog struct {

	// id
	ID int32 `json:"id,omitempty"`

	// time stamp of log, if not set, will be set server-side to the current time
	LoggedAt strfmt.DateTime `json:"loggedAt,omitempty"`

	// message
	// Required: true
	Message *string `json:"message"`

	// id of associated simulation, set server-side, read-only
	SimulationID int32 `json:"simulationId,omitempty"`
}

// Validate validates this simulation log
func (m *SimulationLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SimulationLog) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}
